<div><br><br><br>
    <?php
    $form->setAttribute('id','frm');
    //$form->setAttribute('action', $this->url('bookstore', array('controller' => 'index', 'action' => 'menu')));
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
    <table>
        <tr><td><?php echo $this->formRow($form->get('email')) ?></td></tr>
        <tr><td><?php echo $this->formRow($form->get('password')) ?></td></tr>
    </table><br><br><br>
    <input type="submit" name="login" id="login" value="LOGIN" />
    <?php echo $this->form()->closeTag(); ?>
    <!-- エラーがある場合、ログイン画面にエラーと表示 -->
    <p><?php
        // $errMsg = null;
        //echo $errMsg . 'test';
        ?></p>
</div>