<div>
    <?php $userInfo = $this->data; 
//echo $this->url('bookstore', array('controller' => 'book', 'action' => 'index'));?>
    <br><br><br>
    <p>【ユーザー】：<a href="<?=$this->url('bookstore', array('controller' => 'user')) . '/index'?>"><?=$userInfo->user?></a></p>
    <table>
        <tr><td><a href="<?=$this->url('bookstore', array('controller' => 'book')) . '/index'?>">【書類一覧】</a></td></tr>
        <tr><td><a href="<?=$this->url('bookstore', array('controller' => 'book')) . '/add'?>">【書類登録】</a></td></tr>
        <tr><td></td></tr>
        <tr><td><a href="<?=$this->url('bookstore', array('controller' => 'cart')) . '/index'?>">【カート状況確認】</a></td></tr>
        <tr><td><a href="<?=$this->url('bookstore', array('controller' => 'book')) . '/import'?>">【初期データ登録（データがない場合のみ）】</a></td></tr>
        <tr><td><a href="<?=$this->url('bookstore', array('controller' => 'order')) . '/index'?>">【購入状況確認】</a></td></tr>
        <tr><td></td></tr>
    </table><br><br><br>
</div>
