<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="Content-Style-Type" content="text/css">
        <link href="style.css" rel="stylesheet" type="text/css">
        <title>書類管理システム</title>
    </head>
    <body>
        <div class="header">
            <h1>書類管理システム</h1>
        </div><?php echo $this->url('bookstore',array('controller' => 'book','action' =>'index')).'/index<br>';
        ?>
        <div class="container">
            <br><br><br>
            <table class="no-border">
                <tr><td><a href="<?php //url('bookstore',array('controller' => 'book','action' => 'index'))
                echo $this->url('bookstore',array('controller' => 'book')).'/index'?>">【書類一覧】</a></td></tr>
                <tr><td><a href="./insert.php">【書類登録】</a></td></tr>
                <tr><td></td></tr>
                <tr><td><a href="./showCart.php">【カート状況確認】</a></td></tr>
                <tr><td><a href="./insertIniData.php">【初期データ登録（データがない場合のみ）】</a></td></tr>
                <tr><td><a href="./orderStatus.php">【購入状況確認】</a></td></tr>
                <tr><td></td></tr>
                <tr><td><a href="./logout.php">【ログアウト】</a></td></tr>
            </table><br><br><br>
        </div>
        <div class="footer">
            <hr class="hr-footer">
            <div class="copyright">copyright (c) 2010 all rights reserved.</div>
        </div>
    </body>
</html>