<div>
    <?php $userInfo = $this->data; 
//echo $this->url('bookstore', array('controller' => 'book', 'action' => 'index'));?>
    <br><br><br>
    <p>【ユーザー】：<a href="<?=$this->url('bookstore', array('controller' => 'user')) . '/index'?>"><?=$userInfo->user?></a></p>
    <table>
        <tr><td><a href="<?=$this->url('bookstore', array('controller' => 'book')) . '/index'?>">【BOOK LIST】</a></td></tr>
        <tr><td><a href="<?=$this->url('bookstore', array('controller' => 'book')) . '/add'?>">【ADD BOOKS】</a></td></tr>
        <tr><td></td></tr>
        <tr><td><a href="<?=$this->url('bookstore', array('controller' => 'cart')) . '/index'?>">【MY CART】</a></td></tr>
        <tr><td><a href="<?=$this->url('bookstore', array('controller' => 'order')) . '/index'?>">【MY PURCHASE HISTORY】</a></td></tr>
        <tr><td><a href="<?=$this->url('bookstore', array('controller' => 'book')) . '/import'?>">【THE FIRST TIME TO ADD BOOKS】</a></td></tr>
        <tr><td></td></tr>
    </table><br><br><br>
</div>
