<div><br><br><br>
    <?php
    echo $this->headTitle($this->title);
    $form->setAttribute('id', 'book');
    //$form->setAttribute('action', $this->url('bookstore', array('controller' => 'index', 'action' => 'menu')));
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
    <h3 align='left'> ADD A BOOK</h3>
    <table>
        <tr>
            <td>ISBN:</td><td><?php echo $this->formRow($form->get('ISBN')) ?></td>
        </tr>
        <tr>
            <td>TITLE:</td><td><?php echo $this->formRow($form->get('TITLE')) ?></td>
        </tr>
        <tr>
            <td>SUBTITLE:</td><td><?php echo $this->formRow($form->get('SUBTITLE')) ?></td>
        </tr>
        <tr>
            <td>WRITER:</td><td><?php echo $this->formRow($form->get('WRITER')) ?></td>
        </tr>
        <tr>
            <td>PRICE:</td><td><?php echo $this->formRow($form->get('PRICE')) ?></td>
        </tr>
        <tr>
            <td>CATEGORY:</td><td><?php echo $this->formRow($form->get('CATEGORY')); ?></td>
        </tr>
        <tr>
            <td>COMMENT:</td><td><?php echo $this->formRow($form->get('COMMENT')) ?></td>
        </tr>
        <tr>
            <td><?php if ($this->addFlag === true): ?> <p style="color:red;">Success in adding a book!</p><?php else: ?><input type="submit" name="add" id=" " size="30" value="ADD" /><?php endif; ?></td>
        </tr>
    </table><br><br><br>
    <span>
        <ul>
            <li><a href="<?= $this->url('bookstore', array('controller' => 'book')) . '/index' ?>">GO TO THE BOOK LIST</a></li>
            <li><a href="<?= $this->url('bookstore', array('controller' => 'book')) . '/add' ?>">CONTINUE TO ADD</a></li>
        </ul>
    </span>
    <?php echo $this->form()->closeTag(); ?>
</div>