<div><br><br><br>
    <?php
    $bookInfo = $this->data;
    if (count($bookInfo) > 0):
        ?>
        <table>
            <tr>
                <td>ISBN</td>
                <td>TITLE</td>
                <td>PRICE</td>
            </tr>
            <tr>
                <td><?= $this->escapeHtml($bookInfo->isbn); ?></td>
                <td><?= $this->escapeHtml($bookInfo->title); ?></td>
                <td><?= $this->escapeHtml($bookInfo->price); ?></td>
            </tr>
            <tr><td colspan="3"/><?= '上記の書類を削除してよろしいでしょうか？' ?></tr>
            <tr>
                <td><input type="submit" name="yes" id="yes" value="YES"></td>
                <td><input type="submit" name="no" id="no" value="NO"></td>
            </tr>
        </table><br><br><br>
        <?php
    endif;
    ?>
</div>
