<div><br><br><br>
    <?php
    $bookInfo = $this->data;
    if (count($bookInfo) > 0):
        ?>
    <form action="<?=$this->url('bookstore', array('controller' => 'book')) . '/delete'?>" method="POST">
        <table>
            <tr>
                <td>ISBN</td>
                <td>TITLE</td>
                <td>PRICE</td>
            </tr>
            <tr>
                <td><?= $this->escapeHtml($bookInfo->isbn); ?></td>
                <td><?= $this->escapeHtml($bookInfo->title); ?></td>
                <td><?= $this->escapeHtml($bookInfo->price); ?></td>
            </tr>
            <tr><td colspan="3"/><?= '上記の書類を削除してよろしいでしょうか？' ?></tr>
            <tr>
                <td><input type="submit" name="yes" id="yes" value="YES"></td>
                <td><input type="submit" name="no" id="no" value="NO"></td>
                <td><a href="<?=$this->url('bookstore', array('controller' => 'book')) . '/index'?>">NO</a></td>
            </tr>
        </table><br><br><br>
        </form>
        <?php
    endif;
    ?>
</div>
