<div><br><br><br>
    <?php
    //$this->getRequest()->getPost('foo');$this->getRequest()->getQuery('foo');
    //if ($this->getRequest()->getPost('edit')):
    $bookInfoAfter = $this->dataAfter;
    $bookInfoBefore = $this->dataBefore;
    if (!isset($bookInfoAfter)):
        $form->setAttribute('id', 'frm');
        $form->prepare();
        echo $this->form()->openTag($form);
        if (count($bookInfoBefore) > 0):
            ?>
            <table>
                <tr>
                    <td>ISBN</td>
                    <td>TITLE</td>
                    <td>TITLE(NEW)</td>
                    <td>PRICE</td>
                    <td>PRICE(NEW)</td>
                </tr>
                <tr>
                    <td><?= $this->escapeHtml($bookInfoBefore->isbn); ?></td>
                    <td><?= $this->escapeHtml($bookInfoBefore->title); ?></td>
                    <td><?php echo $this->formRow($form->get('title')) ?></td>
                    <td><?= $this->escapeHtml($bookInfoBefore->price); ?></td>
                    <td><?php echo $this->formRow($form->get('price')) ?></td>
                </tr>
                <tr>
                    <td><input type="submit" name="edit" id="edit" value="UPDATE"></td>
                </tr>
            </table>
        <?php
        endif;
        echo $this->form()->closeTag();
    else:
        ?>
        <table>
            <tr>
                <td>ISBN</td>
                <td>TITLE</td>
                <td>TITLE(NEW)</td>
                <td>PRICE</td>
                <td>PRICE(NEW)</td>
            </tr>
            <tr>
                <td><?= $this->escapeHtml($bookInfoAfter['isbn']); ?></td>
                <td><?= $this->escapeHtml($bookInfoBefore->title); ?></td>
                <td><?= $this->escapeHtml($bookInfoAfter['title']); ?></td>
                <td><?= $this->escapeHtml($bookInfoBefore->price); ?></td>
                <td><?= $this->escapeHtml($bookInfoAfter['price']); ?></td>
            </tr>
            <tr>
                <td><a href="<?= $this->url('bookstore', array('controller' => 'book')) . '/index' ?>">書類一覧へ戻る</a></td>
                <td></td><td></td><td></td>
                <td><a href="<?= $this->url('bookstore', array('controller' => 'book')) . '/edit?id='.$bookInfoAfter['isbn'] ?>">続いて編集</a></td>
            </tr>
        </table>
    <?php
    //endif;
    endif;
    ?>
    <br><br><br>
</div>
