<div>
    <?php
    $bookInfo = $this->bookInfo;
    $form->setAttribute('id', 'book');
    $form->prepare();
    echo $this->form()->openTag($form);
    if (count($bookInfo) > 0) {
        ?>
        <h3 align='left'> EDIT A BOOK</h3>
        <table>
            <tr><td>NO:</td><td><?php echo $this->escapeHtml($bookInfo['NO']); ?></td></tr>
            <tr><td>ISBN:</td><td><?php echo $this->escapeHtml($bookInfo['ISBN']); ?></td></tr>
            <tr><td>TITLE:</td><td><?php echo $this->formRow($form->get('TITLE')->setValue($bookInfo['TITLE'])); ?></td></tr>
            <tr><td>SUBTITLE:</td><td><?php echo $this->formRow($form->get('SUBTITLE')->setValue($bookInfo['SUBTITLE'])); ?></td></tr>
            <tr><td>WRITER:</td><td><?php echo $this->formRow($form->get('WRITER')->setValue($bookInfo['WRITER'])); ?></td></tr>
            <tr><td>PRICE:</td><td><?php echo $this->formRow($form->get('PRICE')->setValue($bookInfo['PRICE'])); ?></td></tr>
            <tr><td>CATEGORY:</td><td><?php echo $this->formRow($form->get('CATEGORY')->setvalue($bookInfo['CATEGORYID'])); ?></td></tr>
            <tr><td>COMMENT:</td><td><?php echo $this->formRow($form->get('COMMENT')->setValue($bookInfo['COMMENT'])); ?></td></tr>
            <tr><td><?php if ($this->editFlag === true){  ?> <p style="color:red;">Success!Back to Home after 3s... </p><?php $this->editFlag = false ?>
                    <meta http-equiv="refresh" content="3;URL=/bookstore/book/index">
            <?php } else{ ?><input type="submit" name="edit" id=" " size="30" value="EDIT"  class="" /><?php } ?></td>
            </tr>
        </table>
    <?php
    }
    echo $this->form()->closeTag();
    ?> 
    <span>
        <ul>
            <li><a href="<?= $this->url('bookstore', array('controller' => 'book')) . '/index' ?>">GO TO THE BOOK LIST</a></li>
        </ul>
    </span>
</div>
