<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="Content-Style-Type" content="text/css">
        <link href="style.css" rel="stylesheet" type="text/css">
        <title>書類管理システム</title>
    </head>
    <body>
        <div class="header">
            <h1>書類管理システム</h1>
            <hr class="hr-header">
        </div>
        <div class="nav">
            <div class="nav-title"></div>
        </div>
        <div class="container">
            <hr class="hr-container"><br><br><br>
            <table class="no-border">

                <tr>
                    <td>ID</td>
                    <td>user</td>
                    <td>password</td>
                    <td>email</td>
                </tr>
                <?php
                $users = $this->data;
                if (count($users) > 0):
                    foreach ($users as $row):
                        ?>
                        <tr>
                            <td><?= $this->escapeHtml($row->id); ?></td>
                            <td><?= $this->escapeHtml($row->user); ?></td>
                            <td><?= $this->escapeHtml($row->password); ?></td>
                            <td><?= $this->escapeHtml($row->email); ?></td>
                        </tr>
                    <?php endforeach;
                endif;?>
                
            </table><br><br><br>
        </div>
        <div class="footer">
            <hr class="hr-footer">
            <div class="copyright">copyright (c) 2010 all rights reserved.</div>
        </div>
    </body>
</html>