<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Bookstore'); ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',));
        ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar">【ユーザー】：<a href="<?=$this->url('bookstore', array('controller' => 'user')) . '/index'?>"><?=$this->sesstion->userInfo['user']?></a></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>"><img src="<?= $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Bookstore') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('bookstore', array('controller' => 'book')) . '/index' ?>"><?= $this->translate('All The Books') ?></a></li><!--【書類一覧:書類登録、書類更新、書類削除、】-->
                        <li class="active"><a href="<?= $this->url('bookstore', array('controller' => 'order')) . '/index' ?>"><?= $this->translate('My Books') ?></a></li><!--【購入履歴】-->
                        <li class="active"><a href="<?= $this->url('bookstore', array('controller' => 'cart')) . '/index' ?>"><?= $this->translate('My Cart') ?></a></li><!--【カート状況確認】-->
                        <li class="active"><a href="<?= $this->url('bookstore', array('controller' => 'book')) . '/import' ?>"><?= $this->translate('Import Books') ?></a></li><!--【初期データ登録（データがない場合のみ）】-->
                        <li class="active"><a href="<?= $this->url('bookstore', array('controller' => 'user')) . '/register' ?>"><?= $this->translate('Create A Account') ?></a></li><!--【ユーザ登録】-->
                        <li class="active"><a href="<?= $this->url('bookstore', array('controller' => 'user')) . '/edit' ?>"><?= $this->translate('Edit My Account') ?></a></li><!--【ユーザ情報管理】-->
                        <li class="active"><a href="<?= $this->url('bookstore', array('controller' => 'book')) . '/signout' ?>"><?= $this->translate('Sign Out') ?></a></li><!--【ログアウト】-->
                        <!--<li class="active"><a href="<?//= $this->url('bookstore',array('controller'=>'book')).'/add' ?>"><?//= $this->translate('Add A Book') ?></a></li>-->
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by SSS.com <?= $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
